### ISSUE TITLE
v0.2.0 and v0.2.1 don't start the live server. Crash log included

### ISSUE THREAD

**Issue by Frankkz** [yandeu/five-server-vscode#41]
**Describe the bug**
Live Server on 0.2.0 and 0.2.1 doesn't work. Clicking Go Live doesn't load it up.
I reverted back to 0.1.13 and didn't encounter this issue.

```2023-05-20 22:34:07.516 [info] Eager extensions activated
2023-05-20 22:34:07.517 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2023-05-20 22:34:07.518 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2023-05-20 22:34:07.522 [info] ExtensionService#_doActivateExtension yandeu.five-server, startup: false, activationEvent: 'onStartupFinished'
2023-05-20 22:34:10.261 [error] Error: ENOENT: no such file or directory, open '/C:/Users/yanni/Projects/five-server-vscode/node_modules/five-server/client/injected.js'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Module.42537 (/home/franky/.vscode-oss/extensions/yandeu.five-server-0.2.1/dist/537.extension.js:8:734991)
    at Function.i (/home/franky/.vscode-oss/extensions/yandeu.five-server-0.2.1/dist/extension.js:2:4732)
    at h (/home/franky/.vscode-oss/extensions/yandeu.five-server-0.2.1/dist/extension.js:2:9883)
    at e.ExtHostCommands._executeContributedCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:133901) fiveServer.start {"value":"yandeu.five-server","_lower":"yandeu.five-server"}
2023-05-20 22:34:11.263 [error] Error: ENOENT: no such file or directory, open '/C:/Users/yanni/Projects/five-server-vscode/node_modules/five-server/client/injected.js'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at Module.42537 (/home/franky/.vscode-oss/extensions/yandeu.five-server-0.2.1/dist/537.extension.js:8:734991)
    at Function.i (/home/franky/.vscode-oss/extensions/yandeu.five-server-0.2.1/dist/extension.js:2:4732)
    at h (/home/franky/.vscode-oss/extensions/yandeu.five-server-0.2.1/dist/extension.js:2:9883)
    at e.ExtHostCommands._executeContributedCommand (/opt/vscodium-bin/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:133901)```

**Comment by yandeu** [comment]
Yeah I messed up.
Can you please try version 0.2.2?

**Comment by Frankkz** [comment]
> Yeah I messed up. Can you please try version 0.2.2?

0.2.2 works :), thanks for the quick fix!
